# Intermediate Neural Network in TensorFlow Example

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/shallow_net_in_tensorflow.ipynb)

#### Load dependencies

In [1]:
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt

#### Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

#### Preprocess data

In [3]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_valid = X_valid.reshape(10000, 784).astype('float32')

In [4]:
X_train /= 255
X_valid /= 255

In [6]:
X_valid[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [5]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

#### Design neural network architecture

In [6]:
model = Sequential()
# hidden layer:
model.add(Dense(64, activation='tanh', input_shape=(784,)))
model.add(Dense(64, activation='tanh'))

# output layer:
model.add(Dense(10, activation='softmax'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [7]:
(64*64)+64

4160

#### Configure model

In [8]:
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1), metrics=['accuracy'])

#### Train!

In [9]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/20
469/469 [==============================] - 2s 3ms/step - loss: 0.4567 - accuracy: 0.8777 - val_loss: 0.2750 - val_accuracy: 0.9208
Epoch 2/20
469/469 [==============================] - 1s 2ms/step - loss: 0.2520 - accuracy: 0.9278 - val_loss: 0.2130 - val_accuracy: 0.9380
Epoch 3/20
469/469 [==============================] - 1s 2ms/step - loss: 0.2009 - accuracy: 0.9421 - val_loss: 0.1852 - val_accuracy: 0.9476
Epoch 4/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1690 - accuracy: 0.9504 - val_loss: 0.1610 - val_accuracy: 0.9509
Epoch 5/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1462 - accuracy: 0.9569 - val_loss: 0.1442 - val_accuracy: 0.9581
Epoch 6/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1290 - accuracy: 0.9624 - val_loss: 0.1300 - val_accuracy: 0.9611
Epoch 7/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1149 - accuracy: 0.9665 - val_loss: 0.1197 - val_accuracy: 0.9640
Epoch 

#### Evaluating model performance

In [11]:
model.evaluate(X_valid, y_valid)

313/313 [==============================] - 0s 897us/step - loss: 0.0811 - accuracy: 0.9747


[0.08105460554361343, 0.9746999740600586]

#### Performing inference

In [12]:
valid_0 = X_valid[0].reshape(1, 784)

In [13]:
model.predict(valid_0)

array([[6.3439038e-06, 6.6777233e-08, 8.3233281e-05, 6.0245709e-04,
        5.2443579e-07, 7.9333103e-07, 2.0453278e-10, 9.9815577e-01,
        9.1420370e-06, 1.1415489e-03]], dtype=float32)

In [14]:
model.predict_classes(valid_0)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([7], dtype=int64)