# Intermediate Neural Network in TensorFlow

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/shallow_net_in_tensorflow.ipynb)

#### Load dependencies

In [1]:
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt

#### Load data

In [3]:
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

#### Preprocess data

In [4]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_valid = X_valid.reshape(10000, 784).astype('float32')

In [5]:
X_train /= 255
X_valid /= 255

In [6]:
X_valid[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [7]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

#### Design neural network architecture

In [8]:
model = Sequential()
# hidden layer:
model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(Dense(64, activation='relu'))

# output layer:
model.add(Dense(10, activation='softmax'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [11]:
(64*64)+64

4160

#### Configure model

In [12]:
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1), metrics=['accuracy'])

#### Train!

In [13]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/20
469/469 [==============================] - 2s 4ms/step - loss: 0.4772 - accuracy: 0.8613 - val_loss: 0.2880 - val_accuracy: 0.9171
Epoch 2/20
469/469 [==============================] - 1s 2ms/step - loss: 0.2290 - accuracy: 0.9340 - val_loss: 0.2043 - val_accuracy: 0.9387
Epoch 3/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1752 - accuracy: 0.9492 - val_loss: 0.1611 - val_accuracy: 0.9513
Epoch 4/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1455 - accuracy: 0.9573 - val_loss: 0.1360 - val_accuracy: 0.9604
Epoch 5/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1241 - accuracy: 0.9634 - val_loss: 0.1221 - val_accuracy: 0.9637
Epoch 6/20
469/469 [==============================] - 1s 2ms/step - loss: 0.1077 - accuracy: 0.9689 - val_loss: 0.1368 - val_accuracy: 0.9583
Epoch 7/20
469/469 [==============================] - 1s 2ms/step - loss: 0.0972 - accuracy: 0.9711 - val_loss: 0.1087 - val_accuracy: 0.9686
Epoch 

#### Evaluating model performance

In [14]:
model.evaluate(X_valid, y_valid)

313/313 [==============================] - 0s 959us/step - loss: 0.0857 - accuracy: 0.9750


[0.08566737174987793, 0.9750000238418579]

#### Performing inference

In [15]:
valid_0 = X_valid[0].reshape(1, 784)

In [16]:
model.predict(valid_0)

array([[3.7136360e-08, 3.5914368e-07, 1.7283219e-05, 1.4369350e-04,
        1.2950755e-09, 1.2796627e-09, 7.3798769e-14, 9.9983215e-01,
        2.8408284e-08, 6.4875021e-06]], dtype=float32)

In [17]:
model.predict_classes(valid_0)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([7], dtype=int64)